spring.application.name=email-writer

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
gemini.api.key=AIzaSyDQUFr8Z0dNE3aa16vqZ7IseyuAV8XxMSE

spring.webflux.client.resolver=dns
server.port=9096
#reactor.netty.dns.ttl=30s
#reactor.netty.dns.query-timeout=10s